/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto.view;
import com.mycompany.projeto.model.Vaga;
import com.mycompany.projeto.conexaodb.ConexaoBanco;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.SQLException;

/**
 *
 * @author beatriz.miranda
 */
public class Vagas extends javax.swing.JFrame {
        Vaga vg = new Vaga();
        String nome;
    /**
     * Creates new form Vagas
     */
    public Vagas() {
        initComponents();
    }
    
    public Vagas(Vaga vg){
        initComponents();
        this.vg = vg;
        nome = this.vg.getNome();
        campoNomeVaga.setText(this.vg.getNome());
        campoLocalVaga.setText(this.vg.getLocal());
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomeVaga = new javax.swing.JLabel();
        labelLocal = new javax.swing.JLabel();
        campoNomeVaga = new javax.swing.JTextField();
        campoLocalVaga = new javax.swing.JTextField();
        btnSalvarVaga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNomeVaga.setText("Nome:");

        labelLocal.setText("Local:");

        btnSalvarVaga.setText("Salvar");
        btnSalvarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarVagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvarVaga)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeVaga)
                            .addComponent(labelLocal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNomeVaga)
                            .addComponent(campoLocalVaga, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeVaga)
                    .addComponent(campoNomeVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoLocalVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLocal))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarVaga)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarVagaActionPerformed
        ConexaoBanco banco = new ConexaoBanco();
        if (vg == null) {
            vg = new Vaga (campoNomeVaga.getText(), campoLocalVaga.getText());
             banco.inserir("vaga (nomevaga,localvaga)",
                "(" + 
                      "\'" + vg.getNome() + "\'" + "," + 
                      "\'" + vg.getLocal() + "\'" 
                    + ")");   
        } else{
            vg = new Vaga (campoNomeVaga.getText(), campoLocalVaga.getText());
            banco.alterar("vaga", 
                    "nomevaga = " + "\'" + vg.getNome() + "\'" + "," +
                    "localvaga = " + "\'" + vg.getLocal() + "\'" +
                    "Where nomevaga = " + "\'" + nome + "\'");
            vg = null;
        } 
        dispose();
        
    try{
        RelatorioVagas rv = new RelatorioVagas();
        rv.setVisible(true);
    }catch(SQLException ex)
            {
        Logger.getLogger(Vagas.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarVagaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt){
        try{
            RelatorioVagas relatorioVagas = new RelatorioVagas();
            relatorioVagas.setVisible(true);
        }
        catch (SQLException ex){
            Logger.getLogger(Vagas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vagas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarVaga;
    private javax.swing.JTextField campoLocalVaga;
    private javax.swing.JTextField campoNomeVaga;
    private javax.swing.JLabel labelLocal;
    private javax.swing.JLabel labelNomeVaga;
    // End of variables declaration//GEN-END:variables
}
